import { ComposeConfig, ServiceConfig } from "@/types/compose";

// ─── Chart.yaml ─────────────────────────────────────────────────────────────

export function generateChartYaml(config: ComposeConfig): string {
  return `apiVersion: v2
name: ${config.projectName}
description: A Helm chart generated by DockerCraft for ${config.projectName}
type: application
version: 0.1.0
appVersion: "1.0.0"
`;
}

// ─── values.yaml ─────────────────────────────────────────────────────────────

export function generateValuesYaml(config: ComposeConfig): string {
  const lines: string[] = [
    `# Default values for ${config.projectName}`,
    `# Generated by DockerCraft`,
    ``,
    `replicaCount: 1`,
    ``,
    `services:`,
  ];

  for (const service of config.services) {
    const image = service.useDockerfile ? `${config.projectName}/${service.name}` : (service.image || "your-image");
    const [repo, tag = "latest"] = image.split(":");
    const port = service.ports[0]?.container ?? 80;

    lines.push(`  ${service.name}:`);
    lines.push(`    image:`);
    lines.push(`      repository: ${repo}`);
    lines.push(`      tag: "${tag}"`);
    lines.push(`      pullPolicy: IfNotPresent`);
    lines.push(`    port: ${port}`);
    lines.push(`    replicaCount: 1`);
    lines.push(`    resources:`);
    lines.push(`      requests:`);
    lines.push(`        memory: "128Mi"`);
    lines.push(`        cpu: "100m"`);
    lines.push(`      limits:`);
    lines.push(`        memory: "512Mi"`);
    lines.push(`        cpu: "500m"`);
  }

  return lines.join("\n") + "\n";
}

// ─── templates/deployment.yaml ───────────────────────────────────────────────

export function generateDeploymentTemplate(config: ComposeConfig): string {
  const docs: string[] = [];

  for (const service of config.services) {
    const port = service.ports[0]?.container ?? 80;

    docs.push(`{{- /* Deployment for ${service.name} */}}`);
    docs.push(`---`);
    docs.push(`apiVersion: apps/v1`);
    docs.push(`kind: Deployment`);
    docs.push(`metadata:`);
    docs.push(`  name: {{ .Release.Name }}-${service.name}`);
    docs.push(`  labels:`);
    docs.push(`    app: {{ .Release.Name }}-${service.name}`);
    docs.push(`spec:`);
    docs.push(`  replicas: {{ .Values.services.${service.name}.replicaCount }}`);
    docs.push(`  selector:`);
    docs.push(`    matchLabels:`);
    docs.push(`      app: {{ .Release.Name }}-${service.name}`);
    docs.push(`  template:`);
    docs.push(`    metadata:`);
    docs.push(`      labels:`);
    docs.push(`        app: {{ .Release.Name }}-${service.name}`);
    docs.push(`    spec:`);
    docs.push(`      containers:`);
    docs.push(`        - name: ${service.name}`);
    docs.push(`          image: "{{ .Values.services.${service.name}.image.repository }}:{{ .Values.services.${service.name}.image.tag }}"`);
    docs.push(`          imagePullPolicy: {{ .Values.services.${service.name}.image.pullPolicy }}`);
    docs.push(`          ports:`);
    docs.push(`            - containerPort: {{ .Values.services.${service.name}.port }}`);
    if (service.environment.length > 0) {
      docs.push(`          env:`);
      for (const { key, value } of service.environment) {
        docs.push(`            - name: ${key}`);
        docs.push(`              value: "${value}"`);
      }
    }
    docs.push(`          resources:`);
    docs.push(`            {{- toYaml .Values.services.${service.name}.resources | nindent 12 }}`);
    docs.push(``);
  }

  return docs.join("\n");
}

// ─── templates/service.yaml ──────────────────────────────────────────────────

export function generateServiceTemplate(config: ComposeConfig): string {
  const docs: string[] = [];

  for (const service of config.services) {
    const port = service.ports[0]?.container ?? 80;

    docs.push(`{{- /* Service for ${service.name} */}}`);
    docs.push(`---`);
    docs.push(`apiVersion: v1`);
    docs.push(`kind: Service`);
    docs.push(`metadata:`);
    docs.push(`  name: {{ .Release.Name }}-${service.name}`);
    docs.push(`spec:`);
    docs.push(`  selector:`);
    docs.push(`    app: {{ .Release.Name }}-${service.name}`);
    docs.push(`  type: ClusterIP`);
    docs.push(`  ports:`);
    docs.push(`    - port: {{ .Values.services.${service.name}.port }}`);
    docs.push(`      targetPort: {{ .Values.services.${service.name}.port }}`);
    docs.push(``);
  }

  return docs.join("\n");
}

// ─── Helm chart file manifest ─────────────────────────────────────────────────

export interface HelmChartFile {
  path: string;
  content: string;
}

export function generateHelmChart(config: ComposeConfig): HelmChartFile[] {
  return [
    { path: "Chart.yaml",                  content: generateChartYaml(config) },
    { path: "values.yaml",                 content: generateValuesYaml(config) },
    { path: "templates/deployment.yaml",   content: generateDeploymentTemplate(config) },
    { path: "templates/service.yaml",      content: generateServiceTemplate(config) },
    {
      path: "templates/_helpers.tpl",
      content: `{{/*\nDockerCraft Helm helpers — add your custom template helpers here.\n*/}}\n`,
    },
  ];
}
