import { ComposeConfig, ServiceConfig } from "@/types/compose";

// ─── Helpers ────────────────────────────────────────────────────────────────

function safeLabel(name: string): string {
  return name.replace(/[^a-z0-9-]/gi, "-").toLowerCase();
}

function renderDeployment(service: ServiceConfig, projectName: string): string {
  const label = safeLabel(service.name);
  const proj = safeLabel(projectName);
  const image = service.useDockerfile ? `${proj}-${label}:latest` : service.image || "your-image:latest";
  const port = service.ports[0]?.container ?? 80;

  const envLines =
    service.environment.length > 0
      ? [
          "        env:",
          ...service.environment.map(
            ({ key, value }) => `          - name: ${key}\n            value: "${value}"`
          ),
        ].join("\n")
      : "";

  return `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${label}
  namespace: default
  labels:
    app: ${label}
    project: ${proj}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${label}
  template:
    metadata:
      labels:
        app: ${label}
    spec:
      containers:
        - name: ${label}
          image: ${image}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: ${port}
              protocol: TCP
${envLines ? envLines + "\n" : ""}          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"`;
}

function renderService(service: ServiceConfig, projectName: string): string {
  const label = safeLabel(service.name);
  const proj = safeLabel(projectName);
  const port = service.ports[0]?.container ?? 80;
  const hostPort = service.ports[0]?.host;
  const serviceType = hostPort && hostPort < 30000 ? "NodePort" : "ClusterIP";

  const nodePortLine = serviceType === "NodePort"
    ? `\n        nodePort: ${Math.max(30000, (hostPort ?? 30000))}`
    : "";

  return `apiVersion: v1
kind: Service
metadata:
  name: ${label}
  namespace: default
  labels:
    app: ${label}
    project: ${proj}
spec:
  selector:
    app: ${label}
  type: ${serviceType}
  ports:
    - name: http
      port: ${port}
      targetPort: ${port}
      protocol: TCP${nodePortLine}`;
}

function renderConfigMap(service: ServiceConfig, projectName: string): string | null {
  // Only render a ConfigMap when there are non-secret env vars
  const publicEnv = service.environment.filter(
    ({ key }) =>
      !key.toLowerCase().includes("password") &&
      !key.toLowerCase().includes("secret") &&
      !key.toLowerCase().includes("token") &&
      !key.toLowerCase().includes("key")
  );

  if (publicEnv.length === 0) return null;

  const label = safeLabel(service.name);
  const proj = safeLabel(projectName);

  const dataLines = publicEnv
    .map(({ key, value }) => `  ${key}: "${value}"`)
    .join("\n");

  return `apiVersion: v1
kind: ConfigMap
metadata:
  name: ${label}-config
  namespace: default
  labels:
    app: ${label}
    project: ${proj}
data:
${dataLines}`;
}

// ─── Main generator ──────────────────────────────────────────────────────────

/**
 * Converts a `ComposeConfig` into a multi-document Kubernetes YAML string.
 * Produces Deployment + Service per service, and optional ConfigMap for
 * non-sensitive environment variables.
 */
export function generateKubernetes(config: ComposeConfig): string {
  const docs: string[] = [];

  docs.push(
    `# Generated by DockerCraft — Kubernetes Manifests`,
    `# Project: ${config.projectName}`,
    `# Apply with: kubectl apply -f k8s-manifests.yaml`,
    ``
  );

  for (const service of config.services) {
    docs.push("---");
    docs.push(renderDeployment(service, config.projectName));
    docs.push("");
    docs.push("---");
    docs.push(renderService(service, config.projectName));

    const cm = renderConfigMap(service, config.projectName);
    if (cm) {
      docs.push("");
      docs.push("---");
      docs.push(cm);
    }

    docs.push("");
  }

  return docs.join("\n");
}
