import { FrameworkTemplate, FrameworkId } from "@/types/dockerfile";

export const FRAMEWORK_TEMPLATES: Record<FrameworkId, FrameworkTemplate> = {
  nodejs: {
    id: "nodejs",
    label: "Node.js",
    category: "JavaScript",
    icon: "⬡",
    color: "#68a063",
    defaultVersion: "20",
    versions: ["20", "18", "16", "21"],
    defaultPort: 3000,
    defaultBuildCmd: "npm ci --only=production",
    defaultStartCmd: "node server.js",
    defaultWorkdir: "/app",
    supportsMultiStage: true,
    packageManager: "npm",
  },
  nextjs: {
    id: "nextjs",
    label: "Next.js",
    category: "JavaScript",
    icon: "▲",
    color: "#ffffff",
    defaultVersion: "20",
    versions: ["20", "18", "21"],
    defaultPort: 3000,
    defaultBuildCmd: "npm run build",
    defaultStartCmd: "npm start",
    defaultWorkdir: "/app",
    supportsMultiStage: true,
    packageManager: "npm",
  },
  "react-vite": {
    id: "react-vite",
    label: "React (Vite)",
    category: "JavaScript",
    icon: "⚡",
    color: "#61dafb",
    defaultVersion: "20",
    versions: ["20", "18"],
    defaultPort: 80,
    defaultBuildCmd: "npm run build",
    defaultStartCmd: "nginx -g 'daemon off;'",
    defaultWorkdir: "/app",
    supportsMultiStage: true,
    packageManager: "npm",
  },
  bun: {
    id: "bun",
    label: "Bun",
    category: "JavaScript",
    icon: "🧅",
    color: "#fbf0df",
    defaultVersion: "1",
    versions: ["1", "latest"],
    defaultPort: 3000,
    defaultBuildCmd: "bun install --production",
    defaultStartCmd: "bun run start",
    defaultWorkdir: "/app",
    supportsMultiStage: false,
    packageManager: "none",
  },
  deno: {
    id: "deno",
    label: "Deno",
    category: "JavaScript",
    icon: "🦕",
    color: "#70ffaf",
    defaultVersion: "2",
    versions: ["2", "1.44", "latest"],
    defaultPort: 8000,
    defaultBuildCmd: "deno cache main.ts",
    defaultStartCmd: "deno run --allow-net --allow-read main.ts",
    defaultWorkdir: "/app",
    supportsMultiStage: false,
    packageManager: "none",
  },
  "python-fastapi": {
    id: "python-fastapi",
    label: "FastAPI",
    category: "Python",
    icon: "🐍",
    color: "#009688",
    defaultVersion: "3.12",
    versions: ["3.12", "3.11", "3.10"],
    defaultPort: 8000,
    defaultBuildCmd: "pip install --no-cache-dir -r requirements.txt",
    defaultStartCmd: "uvicorn main:app --host 0.0.0.0 --port 8000",
    defaultWorkdir: "/app",
    supportsMultiStage: false,
    packageManager: "pip",
  },
  "python-django": {
    id: "python-django",
    label: "Django",
    category: "Python",
    icon: "🦄",
    color: "#092e20",
    defaultVersion: "3.12",
    versions: ["3.12", "3.11", "3.10"],
    defaultPort: 8000,
    defaultBuildCmd: "pip install --no-cache-dir -r requirements.txt",
    defaultStartCmd: "gunicorn myproject.wsgi:application --bind 0.0.0.0:8000",
    defaultWorkdir: "/app",
    supportsMultiStage: false,
    packageManager: "pip",
  },
  "python-flask": {
    id: "python-flask",
    label: "Flask",
    category: "Python",
    icon: "🍶",
    color: "#000000",
    defaultVersion: "3.12",
    versions: ["3.12", "3.11", "3.10"],
    defaultPort: 5000,
    defaultBuildCmd: "pip install --no-cache-dir -r requirements.txt",
    defaultStartCmd: "gunicorn -w 4 -b 0.0.0.0:5000 app:app",
    defaultWorkdir: "/app",
    supportsMultiStage: false,
    packageManager: "pip",
  },
  go: {
    id: "go",
    label: "Go",
    category: "Go",
    icon: "🐹",
    color: "#00add8",
    defaultVersion: "1.22",
    versions: ["1.22", "1.21", "1.20"],
    defaultPort: 8080,
    defaultBuildCmd: "go mod download && go build -o main .",
    defaultStartCmd: "./main",
    defaultWorkdir: "/app",
    supportsMultiStage: true,
    packageManager: "go",
  },
  "java-spring": {
    id: "java-spring",
    label: "Spring Boot",
    category: "Java",
    icon: "☕",
    color: "#6db33f",
    defaultVersion: "21",
    versions: ["21", "17", "11"],
    defaultPort: 8080,
    defaultBuildCmd: "./mvnw package -DskipTests",
    defaultStartCmd: "java -jar app.jar",
    defaultWorkdir: "/app",
    supportsMultiStage: true,
    packageManager: "maven",
  },
  "php-laravel": {
    id: "php-laravel",
    label: "Laravel",
    category: "PHP",
    icon: "🐘",
    color: "#ff2d20",
    defaultVersion: "8.3",
    versions: ["8.3", "8.2", "8.1"],
    defaultPort: 9000,
    defaultBuildCmd: "composer install --no-dev --optimize-autoloader",
    defaultStartCmd: "php-fpm",
    defaultWorkdir: "/var/www",
    supportsMultiStage: false,
    packageManager: "composer",
  },
  rust: {
    id: "rust",
    label: "Rust",
    category: "Rust",
    icon: "🦀",
    color: "#ce412b",
    defaultVersion: "latest",
    versions: ["latest", "1.79", "1.78"],
    defaultPort: 8080,
    defaultBuildCmd: "cargo build --release",
    defaultStartCmd: "./target/release/app",
    defaultWorkdir: "/app",
    supportsMultiStage: true,
    packageManager: "cargo",
  },
  "ruby-rails": {
    id: "ruby-rails",
    label: "Ruby on Rails",
    category: "Ruby",
    icon: "💎",
    color: "#cc342d",
    defaultVersion: "3.3",
    versions: ["3.3", "3.2", "3.1"],
    defaultPort: 3000,
    defaultBuildCmd: "bundle install",
    defaultStartCmd: "rails server -b 0.0.0.0",
    defaultWorkdir: "/app",
    supportsMultiStage: false,
    packageManager: "bundle",
  },
  nginx: {
    id: "nginx",
    label: "Nginx",
    category: "Server",
    icon: "🌐",
    color: "#009639",
    defaultVersion: "alpine",
    versions: ["alpine", "latest", "1.27"],
    defaultPort: 80,
    defaultBuildCmd: "",
    defaultStartCmd: "nginx -g 'daemon off;'",
    defaultWorkdir: "/usr/share/nginx/html",
    supportsMultiStage: false,
    packageManager: "none",
  },
  static: {
    id: "static",
    label: "Static Site",
    category: "Server",
    icon: "📄",
    color: "#4a90e2",
    defaultVersion: "alpine",
    versions: ["alpine", "latest"],
    defaultPort: 80,
    defaultBuildCmd: "",
    defaultStartCmd: "nginx -g 'daemon off;'",
    defaultWorkdir: "/usr/share/nginx/html",
    supportsMultiStage: false,
    packageManager: "none",
  },
};

export const CATEGORIES = [
  "JavaScript",
  "Python",
  "Go",
  "Java",
  "PHP",
  "Rust",
  "Ruby",
  "Server",
];

export const SERVICE_PRESETS = {
  postgres: {
    image: "postgres:16-alpine",
    environment: [
      { key: "POSTGRES_USER", value: "postgres" },
      { key: "POSTGRES_PASSWORD", value: "password" },
      { key: "POSTGRES_DB", value: "mydb" },
    ],
    ports: [{ host: 5432, container: 5432 }],
    volumes: [{ source: "postgres_data", target: "/var/lib/postgresql/data" }],
  },
  mysql: {
    image: "mysql:8.0",
    environment: [
      { key: "MYSQL_ROOT_PASSWORD", value: "rootpassword" },
      { key: "MYSQL_DATABASE", value: "mydb" },
      { key: "MYSQL_USER", value: "user" },
      { key: "MYSQL_PASSWORD", value: "password" },
    ],
    ports: [{ host: 3306, container: 3306 }],
    volumes: [{ source: "mysql_data", target: "/var/lib/mysql" }],
  },
  mongodb: {
    image: "mongo:7.0",
    environment: [
      { key: "MONGO_INITDB_ROOT_USERNAME", value: "admin" },
      { key: "MONGO_INITDB_ROOT_PASSWORD", value: "password" },
    ],
    ports: [{ host: 27017, container: 27017 }],
    volumes: [{ source: "mongo_data", target: "/data/db" }],
  },
  redis: {
    image: "redis:7-alpine",
    environment: [],
    ports: [{ host: 6379, container: 6379 }],
    volumes: [{ source: "redis_data", target: "/data" }],
  },
  nginx: {
    image: "nginx:alpine",
    environment: [],
    ports: [{ host: 80, container: 80 }, { host: 443, container: 443 }],
    volumes: [{ source: "./nginx.conf", target: "/etc/nginx/nginx.conf" }],
  },
  rabbitmq: {
    image: "rabbitmq:3-management-alpine",
    environment: [
      { key: "RABBITMQ_DEFAULT_USER", value: "admin" },
      { key: "RABBITMQ_DEFAULT_PASS", value: "password" },
    ],
    ports: [{ host: 5672, container: 5672 }, { host: 15672, container: 15672 }],
    volumes: [{ source: "rabbitmq_data", target: "/var/lib/rabbitmq" }],
  },
  elasticsearch: {
    image: "elasticsearch:8.13.0",
    environment: [
      { key: "discovery.type", value: "single-node" },
      { key: "ES_JAVA_OPTS", value: "-Xms512m -Xmx512m" },
    ],
    ports: [{ host: 9200, container: 9200 }],
    volumes: [{ source: "es_data", target: "/usr/share/elasticsearch/data" }],
  },
};
