import { DockerfileConfig } from "@/types/dockerfile";
import { ComposeConfig } from "@/types/compose";
import { generateId } from "@/lib/utils";

export interface QuickStartTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  tags: string[];
  dockerfileConfig: Partial<DockerfileConfig>;
  composeConfig: Partial<ComposeConfig>;
}

export const QUICK_START_TEMPLATES: QuickStartTemplate[] = [
  // ── 1. Next.js + PostgreSQL + Redis ──────────────────────────────────────
  {
    id: "nextjs-postgres-redis",
    name: "Next.js Full-Stack",
    description: "Next.js app with PostgreSQL database and Redis cache",
    icon: "⚡",
    tags: ["JavaScript", "PostgreSQL", "Redis"],
    dockerfileConfig: {
      framework: "nextjs",
      version: "20",
      baseImage: "alpine",
      workdir: "/app",
      port: 3000,
      multiStage: true,
      nonRootUser: true,
      healthCheck: true,
      healthCheckPath: "/api/health",
      healthCheckInterval: 30,
      envVars: [
        { key: "DATABASE_URL", value: "postgresql://postgres:password@db:5432/myapp" },
        { key: "REDIS_URL", value: "redis://cache:6379" },
      ],
      buildCommand: "npm ci",
      startCommand: "node server.js",
    },
    composeConfig: {
      projectName: "nextjs-fullstack",
      services: [
        {
          id: generateId(),
          name: "app",
          preset: "custom",
          image: "",
          useDockerfile: true,
          dockerfilePath: "Dockerfile",
          ports: [{ host: 3000, container: 3000 }],
          environment: [
            { key: "NODE_ENV", value: "production" },
            { key: "DATABASE_URL", value: "postgresql://postgres:password@db:5432/myapp" },
            { key: "REDIS_URL", value: "redis://cache:6379" },
          ],
          volumes: [],
          dependsOn: ["db", "cache"],
          restart: "unless-stopped",
          networks: ["app-network"],
          containerName: "nextjs-app",
          command: "",
        },
        {
          id: generateId(),
          name: "db",
          preset: "postgres",
          image: "postgres:16-alpine",
          useDockerfile: false,
          dockerfilePath: "Dockerfile",
          ports: [{ host: 5432, container: 5432 }],
          environment: [
            { key: "POSTGRES_USER", value: "postgres" },
            { key: "POSTGRES_PASSWORD", value: "password" },
            { key: "POSTGRES_DB", value: "myapp" },
          ],
          volumes: [{ source: "postgres_data", target: "/var/lib/postgresql/data" }],
          dependsOn: [],
          restart: "unless-stopped",
          networks: ["app-network"],
          containerName: "nextjs-db",
          command: "",
        },
        {
          id: generateId(),
          name: "cache",
          preset: "redis",
          image: "redis:7-alpine",
          useDockerfile: false,
          dockerfilePath: "Dockerfile",
          ports: [{ host: 6379, container: 6379 }],
          environment: [],
          volumes: [{ source: "redis_data", target: "/data" }],
          dependsOn: [],
          restart: "unless-stopped",
          networks: ["app-network"],
          containerName: "nextjs-cache",
          command: "",
        },
      ],
      networks: ["app-network"],
      volumes: ["postgres_data", "redis_data"],
    },
  },

  // ── 2. FastAPI + PostgreSQL ───────────────────────────────────────────────
  {
    id: "fastapi-postgres",
    name: "FastAPI + PostgreSQL",
    description: "Python FastAPI REST API with PostgreSQL",
    icon: "🐍",
    tags: ["Python", "PostgreSQL", "REST"],
    dockerfileConfig: {
      framework: "python-fastapi",
      version: "3.12",
      baseImage: "slim",
      workdir: "/app",
      port: 8000,
      multiStage: false,
      nonRootUser: true,
      healthCheck: true,
      healthCheckPath: "/health",
      healthCheckInterval: 30,
      envVars: [
        { key: "DATABASE_URL", value: "postgresql://postgres:password@db:5432/api" },
      ],
      buildCommand: "pip install -r requirements.txt",
      startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000",
    },
    composeConfig: {
      projectName: "fastapi-app",
      services: [
        {
          id: generateId(),
          name: "api",
          preset: "custom",
          image: "",
          useDockerfile: true,
          dockerfilePath: "Dockerfile",
          ports: [{ host: 8000, container: 8000 }],
          environment: [
            { key: "DATABASE_URL", value: "postgresql://postgres:password@db:5432/api" },
            { key: "PYTHONPATH", value: "/app" },
          ],
          volumes: [],
          dependsOn: ["db"],
          restart: "unless-stopped",
          networks: ["api-network"],
          containerName: "fastapi-api",
          command: "",
        },
        {
          id: generateId(),
          name: "db",
          preset: "postgres",
          image: "postgres:16-alpine",
          useDockerfile: false,
          dockerfilePath: "Dockerfile",
          ports: [{ host: 5432, container: 5432 }],
          environment: [
            { key: "POSTGRES_USER", value: "postgres" },
            { key: "POSTGRES_PASSWORD", value: "password" },
            { key: "POSTGRES_DB", value: "api" },
          ],
          volumes: [{ source: "pg_data", target: "/var/lib/postgresql/data" }],
          dependsOn: [],
          restart: "unless-stopped",
          networks: ["api-network"],
          containerName: "fastapi-db",
          command: "",
        },
      ],
      networks: ["api-network"],
      volumes: ["pg_data"],
    },
  },

  // ── 3. Go + Redis ─────────────────────────────────────────────────────────
  {
    id: "go-redis",
    name: "Go + Redis",
    description: "High-performance Go API with Redis caching",
    icon: "🚀",
    tags: ["Go", "Redis", "Performance"],
    dockerfileConfig: {
      framework: "go",
      version: "1.22",
      baseImage: "alpine",
      workdir: "/app",
      port: 8080,
      multiStage: true,
      nonRootUser: false,
      healthCheck: true,
      healthCheckPath: "/health",
      healthCheckInterval: 15,
      envVars: [
        { key: "REDIS_URL", value: "redis://cache:6379" },
        { key: "PORT", value: "8080" },
      ],
      buildCommand: "go build -o main .",
      startCommand: "./main",
    },
    composeConfig: {
      projectName: "go-api",
      services: [
        {
          id: generateId(),
          name: "api",
          preset: "custom",
          image: "",
          useDockerfile: true,
          dockerfilePath: "Dockerfile",
          ports: [{ host: 8080, container: 8080 }],
          environment: [
            { key: "REDIS_URL", value: "redis://cache:6379" },
            { key: "PORT", value: "8080" },
          ],
          volumes: [],
          dependsOn: ["cache"],
          restart: "unless-stopped",
          networks: ["go-network"],
          containerName: "go-api",
          command: "",
        },
        {
          id: generateId(),
          name: "cache",
          preset: "redis",
          image: "redis:7-alpine",
          useDockerfile: false,
          dockerfilePath: "Dockerfile",
          ports: [{ host: 6379, container: 6379 }],
          environment: [],
          volumes: [{ source: "redis_data", target: "/data" }],
          dependsOn: [],
          restart: "unless-stopped",
          networks: ["go-network"],
          containerName: "go-cache",
          command: "",
        },
      ],
      networks: ["go-network"],
      volumes: ["redis_data"],
    },
  },

  // ── 4. React Vite + Nginx ─────────────────────────────────────────────────
  {
    id: "react-vite-nginx",
    name: "React SPA + Nginx",
    description: "React Vite app served by production-optimised Nginx",
    icon: "⚛️",
    tags: ["React", "Nginx", "SPA"],
    dockerfileConfig: {
      framework: "react-vite",
      version: "20",
      baseImage: "alpine",
      workdir: "/app",
      port: 80,
      multiStage: true,
      nonRootUser: false,
      healthCheck: false,
      healthCheckPath: "/",
      healthCheckInterval: 30,
      envVars: [
        { key: "VITE_API_URL", value: "https://api.example.com" },
      ],
      buildCommand: "npm ci && npm run build",
      startCommand: "nginx -g 'daemon off;'",
    },
    composeConfig: {
      projectName: "react-spa",
      services: [
        {
          id: generateId(),
          name: "web",
          preset: "nginx",
          image: "",
          useDockerfile: true,
          dockerfilePath: "Dockerfile",
          ports: [{ host: 80, container: 80 }, { host: 443, container: 443 }],
          environment: [],
          volumes: [{ source: "./nginx.conf", target: "/etc/nginx/conf.d/default.conf" }],
          dependsOn: [],
          restart: "unless-stopped",
          networks: ["web-network"],
          containerName: "react-nginx",
          command: "",
        },
      ],
      networks: ["web-network"],
      volumes: [],
    },
  },

  // ── 5. Node.js + MongoDB ──────────────────────────────────────────────────
  {
    id: "nodejs-mongodb",
    name: "Node.js + MongoDB",
    description: "Express.js API with MongoDB database",
    icon: "🌿",
    tags: ["Node.js", "MongoDB", "Express"],
    dockerfileConfig: {
      framework: "nodejs",
      version: "20",
      baseImage: "alpine",
      workdir: "/app",
      port: 3000,
      multiStage: true,
      nonRootUser: true,
      healthCheck: true,
      healthCheckPath: "/api/health",
      healthCheckInterval: 30,
      envVars: [
        { key: "MONGODB_URI", value: "mongodb://mongo:27017/myapp" },
        { key: "PORT", value: "3000" },
      ],
      buildCommand: "npm ci --omit=dev",
      startCommand: "node server.js",
    },
    composeConfig: {
      projectName: "node-mongo",
      services: [
        {
          id: generateId(),
          name: "api",
          preset: "custom",
          image: "",
          useDockerfile: true,
          dockerfilePath: "Dockerfile",
          ports: [{ host: 3000, container: 3000 }],
          environment: [
            { key: "NODE_ENV", value: "production" },
            { key: "MONGODB_URI", value: "mongodb://mongo:27017/myapp" },
          ],
          volumes: [],
          dependsOn: ["mongo"],
          restart: "unless-stopped",
          networks: ["mongo-network"],
          containerName: "node-api",
          command: "",
        },
        {
          id: generateId(),
          name: "mongo",
          preset: "mongodb",
          image: "mongo:7",
          useDockerfile: false,
          dockerfilePath: "Dockerfile",
          ports: [{ host: 27017, container: 27017 }],
          environment: [
            { key: "MONGO_INITDB_ROOT_USERNAME", value: "admin" },
            { key: "MONGO_INITDB_ROOT_PASSWORD", value: "password" },
          ],
          volumes: [{ source: "mongo_data", target: "/data/db" }],
          dependsOn: [],
          restart: "unless-stopped",
          networks: ["mongo-network"],
          containerName: "node-mongo",
          command: "",
        },
      ],
      networks: ["mongo-network"],
      volumes: ["mongo_data"],
    },
  },

  // ── 6. Spring Boot + MySQL ────────────────────────────────────────────────
  {
    id: "spring-mysql",
    name: "Spring Boot + MySQL",
    description: "Java Spring Boot REST API with MySQL database",
    icon: "☕",
    tags: ["Java", "MySQL", "Spring"],
    dockerfileConfig: {
      framework: "java-spring",
      version: "21",
      baseImage: "alpine",
      workdir: "/app",
      port: 8080,
      multiStage: true,
      nonRootUser: true,
      healthCheck: true,
      healthCheckPath: "/actuator/health",
      healthCheckInterval: 60,
      envVars: [
        { key: "SPRING_DATASOURCE_URL", value: "jdbc:mysql://db:3306/myapp" },
        { key: "SPRING_DATASOURCE_USERNAME", value: "root" },
        { key: "SPRING_DATASOURCE_PASSWORD", value: "password" },
      ],
      buildCommand: "./mvnw package -DskipTests",
      startCommand: "java -jar app.jar",
    },
    composeConfig: {
      projectName: "spring-app",
      services: [
        {
          id: generateId(),
          name: "app",
          preset: "custom",
          image: "",
          useDockerfile: true,
          dockerfilePath: "Dockerfile",
          ports: [{ host: 8080, container: 8080 }],
          environment: [
            { key: "SPRING_DATASOURCE_URL", value: "jdbc:mysql://db:3306/myapp" },
            { key: "SPRING_DATASOURCE_USERNAME", value: "root" },
            { key: "SPRING_DATASOURCE_PASSWORD", value: "password" },
            { key: "SPRING_JPA_HIBERNATE_DDL_AUTO", value: "update" },
          ],
          volumes: [],
          dependsOn: ["db"],
          restart: "unless-stopped",
          networks: ["spring-network"],
          containerName: "spring-app",
          command: "",
        },
        {
          id: generateId(),
          name: "db",
          preset: "mysql",
          image: "mysql:8",
          useDockerfile: false,
          dockerfilePath: "Dockerfile",
          ports: [{ host: 3306, container: 3306 }],
          environment: [
            { key: "MYSQL_ROOT_PASSWORD", value: "password" },
            { key: "MYSQL_DATABASE", value: "myapp" },
          ],
          volumes: [{ source: "mysql_data", target: "/var/lib/mysql" }],
          dependsOn: [],
          restart: "unless-stopped",
          networks: ["spring-network"],
          containerName: "spring-db",
          command: "",
        },
      ],
      networks: ["spring-network"],
      volumes: ["mysql_data"],
    },
  },
];
